### ISSUE TITLE
mochify-istanbul doesn't appear to mix well with babelify

### ISSUE THREAD

**Issue by Flaise** [mantoni/mochify.js#116]
When I run a command like this:

    mochify --transform [babelify --optional runtime] --plugin [mochify-istanbul --report cobertura]

I get output like this:

    Error: Line 1: Unexpected token while parsing file:

There is no stack trace. I've successfully run a Browserify transform with Babelify on the same code base so at the moment what it looks like to me is the coverage plugin is running before the Babelify transform, which of course won't work because the first thing it's going to find is an unsupported reserved word, `import`, on line 1. Is there a way to modify this behavior?

**Comment by mantoni** [comment]
Thanks for reporting. This is a difficult problem because mochify-istanbul adds another transform into the mix. Browserify does not offer any way to control the transform ordering via the API. You can only specifying them in a specific order on the command line. From looking into the browserify sources, it seems like they're adding `transform` now before `plugin` while Mochify does it the other way around.

You can check whether the following fixes it: In your local Mochify installation, swap [the plugin registration](https://github.com/mantoni/mochify.js/blob/master/lib/mochify.js#L133) with [the transform registration](https://github.com/mantoni/mochify.js/blob/master/lib/mochify.js#L142). This seems to be closer to the way Browserify registers transforms and plugins and could be adjusted, in case it fixes your issue.

**Comment by mantoni** [comment]
@Flaise Can I ask you to check whether my suggestion works for you?
