### ISSUE TITLE
API Transforms w/ Options

### ISSUE THREAD

**Issue by joshlasdin** [mantoni/mochify.js#62]
How do I specify options for transforms (using more than 1) using the API syntax? Saw this thread: https://github.com/mantoni/mochify.js/issues/39 but I can't find a way to pass options to the transform.

Thanks!

**Comment by leslc** [comment]
I've been looking for an example of passing arguments to "hbsfy" transform via subarg syntax.  Finally got it working and posting for others in case they're searching.

I want to pass in these arguments: 
```
hbsfy --compiler 'require("handlebars")'
```
(Reason for this is that I can't use the hbsfy/runtime because I need to dynamically register partials).

The subarg syntax to do this is:
```
    b = mochify(config.tests.testFiles, {
      transform: { _: [ 'hbsfy' ], compiler: 'require("handlebars")' },
    })
```
